create table item (
                      item_id bigint generated by default as identity,
                      name varchar(255),
                      price double,
                      primary key (item_id)
);

create table order_details (
                               o_id bigint generated by default as identity,
                               amount double,
                               items varchar(255),
                               order_date timestamp,
                               user_id bigint,
                               primary key (o_id)
);

create table user (
                      user_id bigint generated by default as identity,
                      address varchar(255),
                      name varchar(255),
                      password varchar(255),
                      primary key (user_id)
);

create table audit_log (
                           order_id bigint not null,
                           order_date timestamp,
                           order_details varchar(255),
                           total_amount double,
                           user_id bigint,
                           primary key (order_id)
);

insert into item values(1,'Chicken Biriyani' , 249);
insert into item values(2, 'Paneer Biriyani' , 199);
insert into item values(3, 'Chicken Roll', 149);
insert into item values(4, 'Paneer Roll', 129);
insert into item values(5, 'Pepsi' ,59);

Insert into user values(1, 'Pondy','admin','admin123');
Insert into user values(2, 'Bangalore','user','user123');
-- Insert into user values(3, 'Goa','Sam','sam123');
-- Insert into user values(4, 'Chennai','Ramuuuu','ramuuu123');